### ISSUE TITLE
Arguments imply differing number of rows

### ISSUE THREAD

**Issue by ilonazaiats** [NadiaRom/djcourse#2]
Що робити, якщо при збереженні датафрейму вибиває помилку "arguments imply differing number of rows"? Як її виправити?

Error in data.frame(title = titles, date = dates, views = views, link = links) : arguments imply differing number of rows: 300, 330

**Comment by NadiaRom** [comment]
Ця помилка значить, що вектори різної довжини:

```{r}
a <- c(1,2,3,4,5,6,7,8,9)    # тут довжина 9
b <- c(1:8)                         # а тут — 8    

data.frame(a = a, b = b)    # ваша помилка
```
Чому вектори різної довжини у прикладі зі скрейпінгом? Селектори можуть вибирати інші елементи, або ще 1000+1 причин
